-- إضافة الأعمدة الناقصة إلى جدول Customers

-- التحقق من وجود الجدول أولاً
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Customers')
BEGIN
    -- إضافة الأعمدة إذا لم تكن موجودة
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'Code')
        ALTER TABLE Customers ADD Code NVARCHAR(50) NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'Type')
        ALTER TABLE Customers ADD Type INT DEFAULT 1;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'Balance')
        ALTER TABLE Customers ADD Balance DECIMAL(18,2) DEFAULT 0;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'PriceListId')
        ALTER TABLE Customers ADD PriceListId INT NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'CurrencyId')
        ALTER TABLE Customers ADD CurrencyId INT NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'JoinDate')
        ALTER TABLE Customers ADD JoinDate DATETIME2 NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'LastPurchaseDate')
        ALTER TABLE Customers ADD LastPurchaseDate DATETIME2 NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'LastPaymentDate')
        ALTER TABLE Customers ADD LastPaymentDate DATETIME2 NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'TotalPurchases')
        ALTER TABLE Customers ADD TotalPurchases DECIMAL(18,2) DEFAULT 0;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'TotalPayments')
        ALTER TABLE Customers ADD TotalPayments DECIMAL(18,2) DEFAULT 0;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'InvoiceCount')
        ALTER TABLE Customers ADD InvoiceCount INT DEFAULT 0;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'IsVIP')
        ALTER TABLE Customers ADD IsVIP BIT DEFAULT 0;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'DeletedAt')
        ALTER TABLE Customers ADD DeletedAt DATETIME2 NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'CreatedByUserId')
        ALTER TABLE Customers ADD CreatedByUserId INT NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'UpdatedByUserId')
        ALTER TABLE Customers ADD UpdatedByUserId INT NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'CountryId')
        ALTER TABLE Customers ADD CountryId INT NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'ProvinceId')
        ALTER TABLE Customers ADD ProvinceId INT NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'CityId')
        ALTER TABLE Customers ADD CityId INT NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'PrimaryPhoneId')
        ALTER TABLE Customers ADD PrimaryPhoneId INT NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'SecondaryPhoneId')
        ALTER TABLE Customers ADD SecondaryPhoneId INT NULL;
    
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Customers' AND COLUMN_NAME = 'PrimaryEmailId')
        ALTER TABLE Customers ADD PrimaryEmailId INT NULL;
    
    PRINT 'تم إضافة الأعمدة الناقصة بنجاح أو كانت موجودة مسبقاً'
END
ELSE
BEGIN
    PRINT 'جدول Customers غير موجود'
END
